### ISSUE TITLE
wrapper for official API?

### ISSUE THREAD

**Issue by wiiiky** [lyndsysimon/gab#2]
but where can I find the official API documents?

**Comment by lyndsysimon** [comment]
There is no official API documentation at this point for gab.ai, because there is no official public API.

I asked them if I could create that documentation by inferring their existing API and [they asked that I not do so](https://gab.ai/support/posts/1813620):

![image](https://cloud.githubusercontent.com/assets/131414/20527671/3e30c104-b097-11e6-89d4-b5cb2c2de1a6.png)

The path I decided to take was to write this abstraction layer instead, with the idea being that others who want to interact with Gab could do so using it, and ~~if~~ *when* they change their API in a backward-incompatible way we'll be able to make updates in one place to get everyone's code working again as quickly as possible.

**Comment by lyndsysimon** [comment]
Feel free to continue to discuss here, but I'm going to go ahead and close this issue in the interest of keeping things tidy. I would however encourage you to discuss on gab.ai, using the tag `#GabDevs` so others who are interested can participate.
